{% set name = "pyxrf" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a70898faa1dbac3b89c1480ab2128c76d017acd67a8f92333a600907f07df6a7

build:
  noarch: python
  number: 0
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - atom =0.4.3
    - dask
    - distributed
    - jsonschema
    - h5py
    - lmfit
    - matplotlib
    - numba
    - numpy
    - pandas
    - pillow
    - progress
    - pyqt
    - pystackreg
    - pyyaml
    - qtpy
    - requests
    - scikit-image
    - scipy
    - scikit-beam
    - scikit-image
    - tifffile
    - xraylib

test:
  imports:
    - pyxrf
    - pyxrf.api
    - pyxrf.api_dev
    - pyxrf.core
    - pyxrf.core.fitting
    - pyxrf.core.map_processing
    - pyxrf.core.quant_analysis
    - pyxrf.core.utils
    - pyxrf.core.xrf_utils
    - pyxrf.core.yaml_param_files
    - pyxrf.gui_module
    - pyxrf.gui_support
    - pyxrf.model
    - pyxrf.simulation
    - pyxrf.xanes_maps
    - pyxrf.pyxrf_run
    - pyxrf.db_config

about:
  home: http://nsls-ii.github.io/PyXRF
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: X-ray Fluorescence Fitting GUI
  dev_url: https://github.com/NSLS-II/PyXRF

extra:
  recipe-maintainers:
    - tschoonj
