{% set name = "pyxrf" %}
{% set version = "0.0.22" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f3f35fc5e0b6dd9934b8ee6b0f2246f59b6f032a42c7938009bddf2a74399960

build:
  noarch: python
  number: 0
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - atom
    - enaml >=0.10.3
    - h5py
    - ipywidgets
    - jupyter
    - lmfit >=0.8.3
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pyqt >=5.9.2
    - scipy
    - setuptools
    - six
    - scikit-beam >=0.0.17
    - scikit-image

test:
  imports:
    - pyxrf
    - pyxrf.db_config
    - pyxrf.model
    - pyxrf.view

about:
  home: "http://nsls-ii.github.io/PyXRF"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "X-ray Fluorescence Fitting GUI"
  dev_url: "https://github.com/NSLS-II/PyXRF"

extra:
  recipe-maintainers:
    - tschoonj
