travis:
  secure:
    BINSTAR_TOKEN: nnzWMSguONiSA2nTCujXFVpCN0Zo08qHEekK1Rq7I4qsHnWYRU6h/cqju8kCD+gCZRWgUmvlQ8tMEut7ejLmbuHrcaf3/Cn78c9/r/pf+S8sYFguGcLVqb53idAn62Vw7jTpmkzGe20H5GWsvV8UMmpSqy7NHpRe8m2g0hbLjDLffg2AtD6ZkqboPSiCwGTurycQILRbvGDjLYWriTEGeQyivvacnvc8li+2RkAzMp5o2NwmE+RWeIvslfVQiiYKe26NU3E7/FnC0LPuJqbAZ8Ge4uT4iz7FY2d7/unhyjUtCJ+sDdCV1AkMw+JMQ7mu+VKEZ2aHJktnbm2FhpKSHEm5nA77LArMsoa1wPZfNc5Jtw4ATAVTvhTBLoCpQleG0Y4EqSqBZxoa18Jg/INWiggwpQhgLiwvuj8LPzLWJ/AXNMUo5oqwdHIqWVSC/R4N5l1PqsxTlXLsqKuPfYyVj8jbsgpn1xASf8G6ptvBXU8LFPZhVm9Rm9HJ5Z/PcSeERyi94UPppxsJsrY/V87SLuud6EkeWH6XcFY1UgFgO3126OoU1eraq6F2i/K7NhPLo9Ohe/ehEK99sL9JYAVSJP1DFXsQPjKpKZa1dG0Y7Fhrj6sn42VtpsK+EysV0V8CsQyIfUW6ciAN6VsGxfAEidgDnx5HNnGheFzp+Qhb8QY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
